### ISSUE TITLE
Disconnects on Ubuntu

### ISSUE THREAD

**Issue by Servo97** [FricSense/fricsense-python#1]
```shell
(py310) nagababa@zilil:~/Anthony/sensor_data$ fricsense-read 
Connecting to SML - FricSense on /dev/ttyACM0.
Throughput: 78.47 KB/s
Throughput: 70.17 KB/s
Throughput: 68.48 KB/s
Throughput: 70.22 KB/s
Throughput: 70.18 KB/s
Throughput: 70.21 KB/s
Throughput: 70.17 KB/s
Serial port disconnect (probably).
Traceback (most recent call last):
  File "/home/nagababa/Anthony/fricsense-python/src/fricsense/read_serial.py", line 30, in read_serial
    data = ser.read(1000)
  File "/home/nagababa/miniconda3/envs/py310/lib/python3.10/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Closing serial port.
Writing buffer (1.09 MB) to file fricsense_20241024_111323.bin.
Done.
(py310) nagababa@zilil:~/Anthony/sensor_data$ ^C

```

**Comment by Servo97** [comment]
Fixed. Two separate issues:

- Incorrect permissions on mount (needs 0666 for read/write): https://stackoverflow.com/a/27886201
- brltty service stealing the port, causing the disconnect: https://unix.stackexchange.com/a/670637

# Solutions:

## Part one (from https://stackoverflow.com/a/27886201)

```bash
# navigate to rules.d directory
cd /etc/udev/rules.d
#create a new rule file
sudo touch usb_cdc_acm.rules
# open the file
sudo vim my-usb_cdc_acm.rules
# add the following
KERNEL=="ttyACM0", MODE="0666"
```

## Part two (from https://unix.stackexchange.com/a/670637)

Remove udev rules

BRLTTY uses udev rules to get permissions to mess with the TTYs without being root. You can disable these rules by overriding the rules shipped by your distro with /dev/null:

```bash
for f in /usr/lib/udev/rules.d/*brltty*.rules; do
    sudo ln -s /dev/null "/etc/udev/rules.d/$(basename "$f")"
done
sudo udevadm control --reload-rules
```

Disable service

The BRLTTY service is launched by the brltty.path service. This service can be completely prevented from ever starting by running by doing the following:

```bash
sudo systemctl mask brltty.path
Created symlink /etc/systemd/system/brltty.path → /dev/null.
```
Additionally, to extra ensure the service went away, I followed these instructions from (https://askubuntu.com/a/1454639)

```bash
Listing 2: Disabling brltty service 
$ sudo systemctl stop brltty-udev.service
$ sudo systemctl mask brltty-udev.service
Created symlink /etc/systemd/system/brltty-udev.service → /dev/null.
$ sudo systemctl stop brltty.service
$ sudo systemctl disable brltty.service
Unit /etc/systemd/system/brltty.service is masked, ignoring.

```
